### ISSUE TITLE
 Issue Column not found: 1054 Unknown column 'parent_id' in 'field list' on section adding into BO

### ISSUE THREAD

**Issue by isamarin** [cetera-labs/fastsite-cms#19]
`{"success":false,"message":"An exception occurred while executing 'INSERT INTO dir_structure(data_id,lft,rght,level,parent_id) VALUES('48',4,5,3,16)':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'field list'","ext_message":"In file <b>\/var\/www\/mailylog.ru\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php<\/b> on line: 79<br \/><br \/><b>Stack trace:<\/b><br \/>#0 \/var\/www\/mailylog.ru\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(182): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDO\\Exception))<br \/>\n#1 \/var\/www\/mailylog.ru\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(159): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDO\\MySQL\\Driver), Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'An exception oc...')<br \/>\n#2 \/var\/www\/mailylog.ru\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(2226): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDO\\MySQL\\Driver), Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'INSERT INTO dir...', Array)<br \/>\n#3 \/var\/www\/mailylog.ru\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(1313): Doctrine\\DBAL\\Connection->handleExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'INSERT INTO dir...', Array, Array)<br \/>\n#4 \/var\/www\/mailylog.ru\/vendor\/cetera-labs\/cetera-cms\/cms\/include\/classes\/Cetera\/CDBTree.php(112): Doctrine\\DBAL\\Connection->executeQuery('INSERT INTO dir...')<br \/>\n#5 \/var\/www\/mailylog.ru\/vendor\/cetera-labs\/cetera-cms\/cms\/include\/classes\/Cetera\/Section.php(840): Cetera\\CDBTree->insert(16, Array)<br \/>\n#6 \/var\/www\/mailylog.ru\/www\/cms\/include\/action_catalog.php(182): Cetera\\Section->createChild(Array)<br \/>\n#7 {main}","rows":false}`

**Comment by isamarin** [comment]
fixed
